
const replaceExtension = (src, extension) => {
  const extensionIndex = src.lastIndexOf('.');
  return extensionIndex === -1 ? src : `${src.slice(0, extensionIndex)}.${extension}`;
};

/**
 * Uses responsive WebP candidates when supplied, then the image fallback.
 * Other images prefer AVIF, then WebP, before the image fallback.
 * Source files are generated by scripts/optimize-images.js.
 */
const OptimizedImage = ({
  src,
  alt,
  className = '',
  width,
  height,
  priority = false,
  webpSrcSet,
  sizes,
  ...props
}) => (
  <picture>
    {webpSrcSet && <source srcSet={webpSrcSet} sizes={sizes} type="image/webp" />}
    <source srcSet={replaceExtension(src, 'avif')} type="image/avif" />
    {!webpSrcSet && <source srcSet={replaceExtension(src, 'webp')} type="image/webp" />}
    <img
      src={src}
      alt={alt}
      className={className}
      width={width}
      height={height}
      loading={priority ? 'eager' : 'lazy'}
      fetchpriority={priority ? 'high' : undefined}
      decoding="async"
      {...props}
    />
  </picture>
);

export default OptimizedImage;
