import React from 'react';

const replaceExtension = (src, extension) => {
  const extensionIndex = src.lastIndexOf('.');
  return extensionIndex === -1 ? src : `${src.slice(0, extensionIndex)}.${extension}`;
};

/**
 * Serves tracked AVIF and WebP variants with the supplied image as a fallback.
 * Source files are generated by scripts/optimize-images.js.
 */
const OptimizedImage = ({
  src,
  alt,
  className = '',
  width,
  height,
  priority = false,
  ...props
}) => (
  <picture>
    <source srcSet={replaceExtension(src, 'avif')} type="image/avif" />
    <source srcSet={replaceExtension(src, 'webp')} type="image/webp" />
    <img
      src={src}
      alt={alt}
      className={className}
      width={width}
      height={height}
      loading={priority ? 'eager' : 'lazy'}
      fetchpriority={priority ? 'high' : undefined}
      decoding="async"
      {...props}
    />
  </picture>
);

export default OptimizedImage;
